# Generated by Django 4.2.1 on 2023-08-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='custom_contact',
            field=models.CharField(max_length=200),
        ),
    ]
