# Generated by Django 4.2.1 on 2023-08-20 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_supplier_supplier_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
